// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: config.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Config_Config: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var clientVersion: String = String()

  public var serverVersion: String = String()

  public var intFlags: [Config_Config.Flag] = []

  public var moreFlags: Config_Config.MoreFlags {
    get {return _moreFlags ?? Config_Config.MoreFlags()}
    set {_moreFlags = newValue}
  }
  /// Returns true if `moreFlags` has been explicitly set.
  public var hasMoreFlags: Bool {return self._moreFlags != nil}
  /// Clears the value of `moreFlags`. Subsequent reads from it will return its default value.
  public mutating func clearMoreFlags() {self._moreFlags = nil}

  public var deviceInfo: Config_Config.DeviceInfo {
    get {return _deviceInfo ?? Config_Config.DeviceInfo()}
    set {_deviceInfo = newValue}
  }
  /// Returns true if `deviceInfo` has been explicitly set.
  public var hasDeviceInfo: Bool {return self._deviceInfo != nil}
  /// Clears the value of `deviceInfo`. Subsequent reads from it will return its default value.
  public mutating func clearDeviceInfo() {self._deviceInfo = nil}

  /// item 6 seems like a list of device infos without device ID?
  public var countryCode: String = String()

  public var unknownInts: [UInt32] = []

  public var generatedAtMs: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct Flag: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var key: String = String()

    public var value: Int32 = 0

    public var unknownField4: String {
      get {return _unknownField4 ?? String()}
      set {_unknownField4 = newValue}
    }
    /// Returns true if `unknownField4` has been explicitly set.
    public var hasUnknownField4: Bool {return self._unknownField4 != nil}
    /// Clears the value of `unknownField4`. Subsequent reads from it will return its default value.
    public mutating func clearUnknownField4() {self._unknownField4 = nil}

    public var unknownField5: String {
      get {return _unknownField5 ?? String()}
      set {_unknownField5 = newValue}
    }
    /// Returns true if `unknownField5` has been explicitly set.
    public var hasUnknownField5: Bool {return self._unknownField5 != nil}
    /// Clears the value of `unknownField5`. Subsequent reads from it will return its default value.
    public mutating func clearUnknownField5() {self._unknownField5 = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _unknownField4: String? = nil
    fileprivate var _unknownField5: String? = nil
  }

  public struct WrappedFlag: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var key: String = String()

    public var value: Config_Config.WrappedFlag.Value {
      get {return _value ?? Config_Config.WrappedFlag.Value()}
      set {_value = newValue}
    }
    /// Returns true if `value` has been explicitly set.
    public var hasValue: Bool {return self._value != nil}
    /// Clears the value of `value`. Subsequent reads from it will return its default value.
    public mutating func clearValue() {self._value = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public struct Value: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      public var value: Config_Config.WrappedFlag.Value.OneOf_Value? = nil

      public var intVal: Int32 {
        get {
          if case .intVal(let v)? = value {return v}
          return 0
        }
        set {value = .intVal(newValue)}
      }

      public var strVal: String {
        get {
          if case .strVal(let v)? = value {return v}
          return String()
        }
        set {value = .strVal(newValue)}
      }

      public var unknownFields = SwiftProtobuf.UnknownStorage()

      public enum OneOf_Value: Equatable, Sendable {
        case intVal(Int32)
        case strVal(String)

      }

      public init() {}
    }

    public init() {}

    fileprivate var _value: Config_Config.WrappedFlag.Value? = nil
  }

  public struct MoreFlags: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var wrappedFlags: [Config_Config.WrappedFlag] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct DeviceInfo: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var email: String = String()

    public var zero: String = String()

    public var deviceID: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}

  fileprivate var _moreFlags: Config_Config.MoreFlags? = nil
  fileprivate var _deviceInfo: Config_Config.DeviceInfo? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "config"

extension Config_Config: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Config"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}clientVersion\0\u{1}serverVersion\0\u{1}intFlags\0\u{1}moreFlags\0\u{1}deviceInfo\0\u{2}\u{2}countryCode\0\u{1}unknownInts\0\u{1}generatedAtMS\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.clientVersion) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.serverVersion) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.intFlags) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._moreFlags) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._deviceInfo) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.countryCode) }()
      case 8: try { try decoder.decodeRepeatedUInt32Field(value: &self.unknownInts) }()
      case 9: try { try decoder.decodeSingularInt64Field(value: &self.generatedAtMs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.clientVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.clientVersion, fieldNumber: 1)
    }
    if !self.serverVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.serverVersion, fieldNumber: 2)
    }
    if !self.intFlags.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.intFlags, fieldNumber: 3)
    }
    try { if let v = self._moreFlags {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._deviceInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.countryCode.isEmpty {
      try visitor.visitSingularStringField(value: self.countryCode, fieldNumber: 7)
    }
    if !self.unknownInts.isEmpty {
      try visitor.visitPackedUInt32Field(value: self.unknownInts, fieldNumber: 8)
    }
    if self.generatedAtMs != 0 {
      try visitor.visitSingularInt64Field(value: self.generatedAtMs, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Config_Config, rhs: Config_Config) -> Bool {
    if lhs.clientVersion != rhs.clientVersion {return false}
    if lhs.serverVersion != rhs.serverVersion {return false}
    if lhs.intFlags != rhs.intFlags {return false}
    if lhs._moreFlags != rhs._moreFlags {return false}
    if lhs._deviceInfo != rhs._deviceInfo {return false}
    if lhs.countryCode != rhs.countryCode {return false}
    if lhs.unknownInts != rhs.unknownInts {return false}
    if lhs.generatedAtMs != rhs.generatedAtMs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Config_Config.Flag: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Config_Config.protoMessageName + ".Flag"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{1}value\0\u{2}\u{2}unknownField4\0\u{1}unknownField5\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.value) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._unknownField4) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._unknownField5) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    if self.value != 0 {
      try visitor.visitSingularInt32Field(value: self.value, fieldNumber: 2)
    }
    try { if let v = self._unknownField4 {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._unknownField5 {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Config_Config.Flag, rhs: Config_Config.Flag) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.value != rhs.value {return false}
    if lhs._unknownField4 != rhs._unknownField4 {return false}
    if lhs._unknownField5 != rhs._unknownField5 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Config_Config.WrappedFlag: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Config_Config.protoMessageName + ".WrappedFlag"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{1}value\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._value) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    try { if let v = self._value {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Config_Config.WrappedFlag, rhs: Config_Config.WrappedFlag) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs._value != rhs._value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Config_Config.WrappedFlag.Value: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Config_Config.WrappedFlag.protoMessageName + ".Value"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}intVal\0\u{1}strVal\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try {
        var v: Int32?
        try decoder.decodeSingularInt32Field(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .intVal(v)
        }
      }()
      case 3: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .strVal(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.value {
    case .intVal?: try {
      guard case .intVal(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    }()
    case .strVal?: try {
      guard case .strVal(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Config_Config.WrappedFlag.Value, rhs: Config_Config.WrappedFlag.Value) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Config_Config.MoreFlags: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Config_Config.protoMessageName + ".MoreFlags"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}wrappedFlags\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.wrappedFlags) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.wrappedFlags.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.wrappedFlags, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Config_Config.MoreFlags, rhs: Config_Config.MoreFlags) -> Bool {
    if lhs.wrappedFlags != rhs.wrappedFlags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Config_Config.DeviceInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Config_Config.protoMessageName + ".DeviceInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}email\0\u{1}zero\0\u{1}deviceID\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularStringField(value: &self.email) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.zero) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.email.isEmpty {
      try visitor.visitSingularStringField(value: self.email, fieldNumber: 2)
    }
    if !self.zero.isEmpty {
      try visitor.visitSingularStringField(value: self.zero, fieldNumber: 3)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Config_Config.DeviceInfo, rhs: Config_Config.DeviceInfo) -> Bool {
    if lhs.email != rhs.email {return false}
    if lhs.zero != rhs.zero {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
