// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: settings.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Settings_Settings: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var simcards: [Settings_SIMCard] {
    get {return _storage._simcards}
    set {_uniqueStorage()._simcards = newValue}
  }

  public var opCodeData: Settings_SomeData {
    get {return _storage._opCodeData ?? Settings_SomeData()}
    set {_uniqueStorage()._opCodeData = newValue}
  }
  /// Returns true if `opCodeData` has been explicitly set.
  public var hasOpCodeData: Bool {return _storage._opCodeData != nil}
  /// Clears the value of `opCodeData`. Subsequent reads from it will return its default value.
  public mutating func clearOpCodeData() {_uniqueStorage()._opCodeData = nil}

  public var rcssettings: Settings_RCSSettings {
    get {return _storage._rcssettings ?? Settings_RCSSettings()}
    set {_uniqueStorage()._rcssettings = newValue}
  }
  /// Returns true if `rcssettings` has been explicitly set.
  public var hasRcssettings: Bool {return _storage._rcssettings != nil}
  /// Clears the value of `rcssettings`. Subsequent reads from it will return its default value.
  public mutating func clearRcssettings() {_uniqueStorage()._rcssettings = nil}

  public var bugleVersion: String {
    get {return _storage._bugleVersion}
    set {_uniqueStorage()._bugleVersion = newValue}
  }

  public var bool1: Bool {
    get {return _storage._bool1}
    set {_uniqueStorage()._bool1 = newValue}
  }

  public var boolFields2: Settings_BooleanFields2 {
    get {return _storage._boolFields2 ?? Settings_BooleanFields2()}
    set {_uniqueStorage()._boolFields2 = newValue}
  }
  /// Returns true if `boolFields2` has been explicitly set.
  public var hasBoolFields2: Bool {return _storage._boolFields2 != nil}
  /// Clears the value of `boolFields2`. Subsequent reads from it will return its default value.
  public mutating func clearBoolFields2() {_uniqueStorage()._boolFields2 = nil}

  public var mysteriousBytes: Data {
    get {return _storage._mysteriousBytes}
    set {_uniqueStorage()._mysteriousBytes = newValue}
  }

  public var boolFields3: Settings_BooleanFields3 {
    get {return _storage._boolFields3 ?? Settings_BooleanFields3()}
    set {_uniqueStorage()._boolFields3 = newValue}
  }
  /// Returns true if `boolFields3` has been explicitly set.
  public var hasBoolFields3: Bool {return _storage._boolFields3 != nil}
  /// Clears the value of `boolFields3`. Subsequent reads from it will return its default value.
  public mutating func clearBoolFields3() {_uniqueStorage()._boolFields3 = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Settings_SIMCard: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var rcschats: Settings_RCSChats {
    get {return _rcschats ?? Settings_RCSChats()}
    set {_rcschats = newValue}
  }
  /// Returns true if `rcschats` has been explicitly set.
  public var hasRcschats: Bool {return self._rcschats != nil}
  /// Clears the value of `rcschats`. Subsequent reads from it will return its default value.
  public mutating func clearRcschats() {self._rcschats = nil}

  public var simdata: Settings_SIMData {
    get {return _simdata ?? Settings_SIMData()}
    set {_simdata = newValue}
  }
  /// Returns true if `simdata` has been explicitly set.
  public var hasSimdata: Bool {return self._simdata != nil}
  /// Clears the value of `simdata`. Subsequent reads from it will return its default value.
  public mutating func clearSimdata() {self._simdata = nil}

  public var bool1: Bool = false

  public var simparticipant: Settings_SIMParticipant {
    get {return _simparticipant ?? Settings_SIMParticipant()}
    set {_simparticipant = newValue}
  }
  /// Returns true if `simparticipant` has been explicitly set.
  public var hasSimparticipant: Bool {return self._simparticipant != nil}
  /// Clears the value of `simparticipant`. Subsequent reads from it will return its default value.
  public mutating func clearSimparticipant() {self._simparticipant = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _rcschats: Settings_RCSChats? = nil
  fileprivate var _simdata: Settings_SIMData? = nil
  fileprivate var _simparticipant: Settings_SIMParticipant? = nil
}

public struct Settings_RCSChats: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var enabled: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Settings_BoolMsg: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var bool1: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Settings_SIMPayload: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 1 for payloads in non-self participants?
  public var two: Int32 = 0

  public var simnumber: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Settings_SIMData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var simpayload: Settings_SIMPayload {
    get {return _simpayload ?? Settings_SIMPayload()}
    set {_simpayload = newValue}
  }
  /// Returns true if `simpayload` has been explicitly set.
  public var hasSimpayload: Bool {return self._simpayload != nil}
  /// Clears the value of `simpayload`. Subsequent reads from it will return its default value.
  public mutating func clearSimpayload() {self._simpayload = nil}

  /// maybe isDefault?
  public var bool1: Bool = false

  public var carrierName: String = String()

  public var colorHex: String = String()

  public var int1: Int64 = 0

  public var formattedPhoneNumber: String = String()

  public var internationalPhoneNumber: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _simpayload: Settings_SIMPayload? = nil
}

public struct Settings_UnknownMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var int1: Int64 = 0

  public var int2: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Settings_SIMParticipant: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Settings_SomeData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var pushEnabled: Bool = false

  public var field7: Bool = false

  public var field12: Bool = false

  public var someEmojis: [Data] = []

  public var jsonData: String = String()

  public var someString: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Settings_RCSSettings: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var isEnabled: Bool = false

  public var sendReadReceipts: Bool = false

  public var showTypingIndicators: Bool = false

  /// uncertain, but this field seems to disappear when gmessages is un-defaulted
  public var isDefaultSmsapp: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Settings_BooleanFields2: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var bool1: Bool = false

  public var bool2: Bool = false

  public var boolMsg1: Settings_BoolMsg {
    get {return _boolMsg1 ?? Settings_BoolMsg()}
    set {_boolMsg1 = newValue}
  }
  /// Returns true if `boolMsg1` has been explicitly set.
  public var hasBoolMsg1: Bool {return self._boolMsg1 != nil}
  /// Clears the value of `boolMsg1`. Subsequent reads from it will return its default value.
  public mutating func clearBoolMsg1() {self._boolMsg1 = nil}

  public var boolMsg2: Settings_BoolMsg {
    get {return _boolMsg2 ?? Settings_BoolMsg()}
    set {_boolMsg2 = newValue}
  }
  /// Returns true if `boolMsg2` has been explicitly set.
  public var hasBoolMsg2: Bool {return self._boolMsg2 != nil}
  /// Clears the value of `boolMsg2`. Subsequent reads from it will return its default value.
  public mutating func clearBoolMsg2() {self._boolMsg2 = nil}

  public var bool3: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _boolMsg1: Settings_BoolMsg? = nil
  fileprivate var _boolMsg2: Settings_BoolMsg? = nil
}

public struct Settings_BooleanFields3: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var bool1: Bool = false

  public var bool3: Bool = false

  public var bool4: Bool = false

  public var bool5: Bool = false

  public var bool6: Bool = false

  public var bool7: Bool = false

  public var bool8: Bool = false

  public var bool9: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "settings"

extension Settings_Settings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Settings"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}SIMCards\0\u{1}opCodeData\0\u{1}RCSSettings\0\u{1}bugleVersion\0\u{2}\u{2}bool1\0\u{1}boolFields2\0\u{1}mysteriousBytes\0\u{1}boolFields3\0")

  fileprivate class _StorageClass {
    var _simcards: [Settings_SIMCard] = []
    var _opCodeData: Settings_SomeData? = nil
    var _rcssettings: Settings_RCSSettings? = nil
    var _bugleVersion: String = String()
    var _bool1: Bool = false
    var _boolFields2: Settings_BooleanFields2? = nil
    var _mysteriousBytes: Data = Data()
    var _boolFields3: Settings_BooleanFields3? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _simcards = source._simcards
      _opCodeData = source._opCodeData
      _rcssettings = source._rcssettings
      _bugleVersion = source._bugleVersion
      _bool1 = source._bool1
      _boolFields2 = source._boolFields2
      _mysteriousBytes = source._mysteriousBytes
      _boolFields3 = source._boolFields3
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 2: try { try decoder.decodeRepeatedMessageField(value: &_storage._simcards) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._opCodeData) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._rcssettings) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._bugleVersion) }()
        case 7: try { try decoder.decodeSingularBoolField(value: &_storage._bool1) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._boolFields2) }()
        case 9: try { try decoder.decodeSingularBytesField(value: &_storage._mysteriousBytes) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._boolFields3) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._simcards.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._simcards, fieldNumber: 2)
      }
      try { if let v = _storage._opCodeData {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._rcssettings {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      if !_storage._bugleVersion.isEmpty {
        try visitor.visitSingularStringField(value: _storage._bugleVersion, fieldNumber: 5)
      }
      if _storage._bool1 != false {
        try visitor.visitSingularBoolField(value: _storage._bool1, fieldNumber: 7)
      }
      try { if let v = _storage._boolFields2 {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      if !_storage._mysteriousBytes.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._mysteriousBytes, fieldNumber: 9)
      }
      try { if let v = _storage._boolFields3 {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Settings_Settings, rhs: Settings_Settings) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._simcards != rhs_storage._simcards {return false}
        if _storage._opCodeData != rhs_storage._opCodeData {return false}
        if _storage._rcssettings != rhs_storage._rcssettings {return false}
        if _storage._bugleVersion != rhs_storage._bugleVersion {return false}
        if _storage._bool1 != rhs_storage._bool1 {return false}
        if _storage._boolFields2 != rhs_storage._boolFields2 {return false}
        if _storage._mysteriousBytes != rhs_storage._mysteriousBytes {return false}
        if _storage._boolFields3 != rhs_storage._boolFields3 {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Settings_SIMCard: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SIMCard"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{3}RCSChats\0\u{2}\u{2}SIMData\0\u{1}bool1\0\u{1}SIMParticipant\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 3: try { try decoder.decodeSingularMessageField(value: &self._rcschats) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._simdata) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.bool1) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._simparticipant) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._rcschats {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._simdata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if self.bool1 != false {
      try visitor.visitSingularBoolField(value: self.bool1, fieldNumber: 6)
    }
    try { if let v = self._simparticipant {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Settings_SIMCard, rhs: Settings_SIMCard) -> Bool {
    if lhs._rcschats != rhs._rcschats {return false}
    if lhs._simdata != rhs._simdata {return false}
    if lhs.bool1 != rhs.bool1 {return false}
    if lhs._simparticipant != rhs._simparticipant {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Settings_RCSChats: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RCSChats"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}enabled\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enabled) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.enabled != false {
      try visitor.visitSingularBoolField(value: self.enabled, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Settings_RCSChats, rhs: Settings_RCSChats) -> Bool {
    if lhs.enabled != rhs.enabled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Settings_BoolMsg: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BoolMsg"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}bool1\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.bool1) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.bool1 != false {
      try visitor.visitSingularBoolField(value: self.bool1, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Settings_BoolMsg, rhs: Settings_BoolMsg) -> Bool {
    if lhs.bool1 != rhs.bool1 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Settings_SIMPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SIMPayload"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}two\0\u{1}SIMNumber\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.two) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.simnumber) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.two != 0 {
      try visitor.visitSingularInt32Field(value: self.two, fieldNumber: 1)
    }
    if self.simnumber != 0 {
      try visitor.visitSingularInt32Field(value: self.simnumber, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Settings_SIMPayload, rhs: Settings_SIMPayload) -> Bool {
    if lhs.two != rhs.two {return false}
    if lhs.simnumber != rhs.simnumber {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Settings_SIMData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SIMData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}SIMPayload\0\u{1}bool1\0\u{1}carrierName\0\u{1}colorHex\0\u{1}int1\0\u{1}formattedPhoneNumber\0\u{1}internationalPhoneNumber\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._simpayload) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.bool1) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.carrierName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.colorHex) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.int1) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.formattedPhoneNumber) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.internationalPhoneNumber) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._simpayload {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.bool1 != false {
      try visitor.visitSingularBoolField(value: self.bool1, fieldNumber: 2)
    }
    if !self.carrierName.isEmpty {
      try visitor.visitSingularStringField(value: self.carrierName, fieldNumber: 3)
    }
    if !self.colorHex.isEmpty {
      try visitor.visitSingularStringField(value: self.colorHex, fieldNumber: 4)
    }
    if self.int1 != 0 {
      try visitor.visitSingularInt64Field(value: self.int1, fieldNumber: 5)
    }
    if !self.formattedPhoneNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.formattedPhoneNumber, fieldNumber: 6)
    }
    if !self.internationalPhoneNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.internationalPhoneNumber, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Settings_SIMData, rhs: Settings_SIMData) -> Bool {
    if lhs._simpayload != rhs._simpayload {return false}
    if lhs.bool1 != rhs.bool1 {return false}
    if lhs.carrierName != rhs.carrierName {return false}
    if lhs.colorHex != rhs.colorHex {return false}
    if lhs.int1 != rhs.int1 {return false}
    if lhs.formattedPhoneNumber != rhs.formattedPhoneNumber {return false}
    if lhs.internationalPhoneNumber != rhs.internationalPhoneNumber {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Settings_UnknownMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UnknownMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}int1\0\u{1}int2\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.int1) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.int2) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.int1 != 0 {
      try visitor.visitSingularInt64Field(value: self.int1, fieldNumber: 1)
    }
    if self.int2 != 0 {
      try visitor.visitSingularInt64Field(value: self.int2, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Settings_UnknownMessage, rhs: Settings_UnknownMessage) -> Bool {
    if lhs.int1 != rhs.int1 {return false}
    if lhs.int2 != rhs.int2 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Settings_SIMParticipant: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SIMParticipant"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ID\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Settings_SIMParticipant, rhs: Settings_SIMParticipant) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Settings_SomeData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SomeData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{3}pushEnabled\0\u{2}\u{4}field7\0\u{2}\u{5}field12\0\u{2}\u{3}someEmojis\0\u{1}jsonData\0\u{1}someString\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 3: try { try decoder.decodeSingularBoolField(value: &self.pushEnabled) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.field7) }()
      case 12: try { try decoder.decodeSingularBoolField(value: &self.field12) }()
      case 15: try { try decoder.decodeRepeatedBytesField(value: &self.someEmojis) }()
      case 16: try { try decoder.decodeSingularStringField(value: &self.jsonData) }()
      case 17: try { try decoder.decodeSingularStringField(value: &self.someString) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.pushEnabled != false {
      try visitor.visitSingularBoolField(value: self.pushEnabled, fieldNumber: 3)
    }
    if self.field7 != false {
      try visitor.visitSingularBoolField(value: self.field7, fieldNumber: 7)
    }
    if self.field12 != false {
      try visitor.visitSingularBoolField(value: self.field12, fieldNumber: 12)
    }
    if !self.someEmojis.isEmpty {
      try visitor.visitRepeatedBytesField(value: self.someEmojis, fieldNumber: 15)
    }
    if !self.jsonData.isEmpty {
      try visitor.visitSingularStringField(value: self.jsonData, fieldNumber: 16)
    }
    if !self.someString.isEmpty {
      try visitor.visitSingularStringField(value: self.someString, fieldNumber: 17)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Settings_SomeData, rhs: Settings_SomeData) -> Bool {
    if lhs.pushEnabled != rhs.pushEnabled {return false}
    if lhs.field7 != rhs.field7 {return false}
    if lhs.field12 != rhs.field12 {return false}
    if lhs.someEmojis != rhs.someEmojis {return false}
    if lhs.jsonData != rhs.jsonData {return false}
    if lhs.someString != rhs.someString {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Settings_RCSSettings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RCSSettings"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}isEnabled\0\u{1}sendReadReceipts\0\u{1}showTypingIndicators\0\u{1}isDefaultSMSApp\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.isEnabled) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.sendReadReceipts) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.showTypingIndicators) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isDefaultSmsapp) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.isEnabled != false {
      try visitor.visitSingularBoolField(value: self.isEnabled, fieldNumber: 1)
    }
    if self.sendReadReceipts != false {
      try visitor.visitSingularBoolField(value: self.sendReadReceipts, fieldNumber: 2)
    }
    if self.showTypingIndicators != false {
      try visitor.visitSingularBoolField(value: self.showTypingIndicators, fieldNumber: 3)
    }
    if self.isDefaultSmsapp != false {
      try visitor.visitSingularBoolField(value: self.isDefaultSmsapp, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Settings_RCSSettings, rhs: Settings_RCSSettings) -> Bool {
    if lhs.isEnabled != rhs.isEnabled {return false}
    if lhs.sendReadReceipts != rhs.sendReadReceipts {return false}
    if lhs.showTypingIndicators != rhs.showTypingIndicators {return false}
    if lhs.isDefaultSmsapp != rhs.isDefaultSmsapp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Settings_BooleanFields2: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BooleanFields2"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}bool1\0\u{1}bool2\0\u{1}boolMsg1\0\u{2}\u{2}boolMsg2\0\u{1}bool3\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.bool1) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.bool2) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._boolMsg1) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._boolMsg2) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.bool3) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.bool1 != false {
      try visitor.visitSingularBoolField(value: self.bool1, fieldNumber: 1)
    }
    if self.bool2 != false {
      try visitor.visitSingularBoolField(value: self.bool2, fieldNumber: 2)
    }
    try { if let v = self._boolMsg1 {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._boolMsg2 {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if self.bool3 != false {
      try visitor.visitSingularBoolField(value: self.bool3, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Settings_BooleanFields2, rhs: Settings_BooleanFields2) -> Bool {
    if lhs.bool1 != rhs.bool1 {return false}
    if lhs.bool2 != rhs.bool2 {return false}
    if lhs._boolMsg1 != rhs._boolMsg1 {return false}
    if lhs._boolMsg2 != rhs._boolMsg2 {return false}
    if lhs.bool3 != rhs.bool3 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Settings_BooleanFields3: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BooleanFields3"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}bool1\0\u{2}\u{2}bool3\0\u{1}bool4\0\u{1}bool5\0\u{1}bool6\0\u{1}bool7\0\u{1}bool8\0\u{1}bool9\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.bool1) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.bool3) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.bool4) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.bool5) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.bool6) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.bool7) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.bool8) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self.bool9) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.bool1 != false {
      try visitor.visitSingularBoolField(value: self.bool1, fieldNumber: 1)
    }
    if self.bool3 != false {
      try visitor.visitSingularBoolField(value: self.bool3, fieldNumber: 3)
    }
    if self.bool4 != false {
      try visitor.visitSingularBoolField(value: self.bool4, fieldNumber: 4)
    }
    if self.bool5 != false {
      try visitor.visitSingularBoolField(value: self.bool5, fieldNumber: 5)
    }
    if self.bool6 != false {
      try visitor.visitSingularBoolField(value: self.bool6, fieldNumber: 6)
    }
    if self.bool7 != false {
      try visitor.visitSingularBoolField(value: self.bool7, fieldNumber: 7)
    }
    if self.bool8 != false {
      try visitor.visitSingularBoolField(value: self.bool8, fieldNumber: 8)
    }
    if self.bool9 != false {
      try visitor.visitSingularBoolField(value: self.bool9, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Settings_BooleanFields3, rhs: Settings_BooleanFields3) -> Bool {
    if lhs.bool1 != rhs.bool1 {return false}
    if lhs.bool3 != rhs.bool3 {return false}
    if lhs.bool4 != rhs.bool4 {return false}
    if lhs.bool5 != rhs.bool5 {return false}
    if lhs.bool6 != rhs.bool6 {return false}
    if lhs.bool7 != rhs.bool7 {return false}
    if lhs.bool8 != rhs.bool8 {return false}
    if lhs.bool9 != rhs.bool9 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
